import {
  SCANNER_ACTION_COMMAND,
  SCANNER_ACTION_RESPONSE,
  SCANNER_BOOTSTRAP_COMMAND,
  SCANNER_BOOTSTRAP_RESPONSE,
  SCANNER_DOM_REVIEW_RESPONSE_OPERATION,
  SCANNER_OPERATIONS,
  SCANNER_REQUEST_SUPPORT_ELEMENTS_OPERATION,
  SCANNER_REQUEST_SUPPORT_OPERATION,
  SCANNER_SEARCH_TERMS_OPERATION,
  SCANNER_SEND_DOM_REVIEW_OPERATION,
  SCANNER_STATE_EVENT,
  SCANNER_SUPPORT_REQUEST_ELEMENTS_RESPONSE_OPERATION,
  SCANNER_SUPPORT_REQUEST_RESPONSE_OPERATION,
} from './Scanner.operations';

test('keeps scanner websocket command and operation ids stable', () => {
  expect(SCANNER_BOOTSTRAP_COMMAND).toBe('scanner.bootstrap');
  expect(SCANNER_ACTION_COMMAND).toBe('scanner.action');
  expect(SCANNER_BOOTSTRAP_RESPONSE).toBe('scanner.bootstrapResponse');
  expect(SCANNER_ACTION_RESPONSE).toBe('scanner.actionResponse');
  expect(SCANNER_STATE_EVENT).toBe('scanner.state');
  expect(SCANNER_SEARCH_TERMS_OPERATION).toBe('searchTerms');
  expect(SCANNER_SEND_DOM_REVIEW_OPERATION).toBe('SEND_DOM_REVIEW');
  expect(SCANNER_REQUEST_SUPPORT_OPERATION).toBe('REQUEST_SUPPORT');
  expect(SCANNER_REQUEST_SUPPORT_ELEMENTS_OPERATION).toBe('REQUEST_SUPPORT_ELEMENTS');
  expect(SCANNER_DOM_REVIEW_RESPONSE_OPERATION).toBe('DOM_REVIEW_RESPONSE');
  expect(SCANNER_SUPPORT_REQUEST_RESPONSE_OPERATION).toBe('SUPPORT_REQUEST_RESPONSE');
  expect(SCANNER_SUPPORT_REQUEST_ELEMENTS_RESPONSE_OPERATION).toBe('SUPPORT_REQUEST_ELEMENTS_RESPONSE');
  expect(SCANNER_OPERATIONS.has(SCANNER_BOOTSTRAP_RESPONSE)).toBe(true);
  expect(SCANNER_OPERATIONS.has(SCANNER_ACTION_RESPONSE)).toBe(true);
  expect(SCANNER_OPERATIONS.has(SCANNER_STATE_EVENT)).toBe(true);
});
