export const SCANNER_BOOTSTRAP_COMMAND = 'scanner.bootstrap';
export const SCANNER_ACTION_COMMAND = 'scanner.action';

export const SCANNER_BOOTSTRAP_RESPONSE = 'scanner.bootstrapResponse';
export const SCANNER_ACTION_RESPONSE = 'scanner.actionResponse';
export const SCANNER_STATE_EVENT = 'scanner.state';
export const SCANNER_SEARCH_TERMS_OPERATION = 'searchTerms';
export const SCANNER_SEND_DOM_REVIEW_OPERATION = 'SEND_DOM_REVIEW';
export const SCANNER_REQUEST_SUPPORT_OPERATION = 'REQUEST_SUPPORT';
export const SCANNER_REQUEST_SUPPORT_ELEMENTS_OPERATION = 'REQUEST_SUPPORT_ELEMENTS';
export const SCANNER_DOM_REVIEW_RESPONSE_OPERATION = 'DOM_REVIEW_RESPONSE';
export const SCANNER_SUPPORT_REQUEST_RESPONSE_OPERATION = 'SUPPORT_REQUEST_RESPONSE';
export const SCANNER_SUPPORT_REQUEST_ELEMENTS_RESPONSE_OPERATION = 'SUPPORT_REQUEST_ELEMENTS_RESPONSE';

export const SCANNER_OPERATIONS = new Set([
  SCANNER_BOOTSTRAP_RESPONSE,
  SCANNER_ACTION_RESPONSE,
  SCANNER_STATE_EVENT,
]);
