// Sample data (mocketData)
export interface BlockLoopInstructionLoadDTO {
  homeBankingId: number;
  botJobId: number;
  botJobName: string;
  id: number;
  instructionOrderNumber: number;
  name: string;
  description: string;
  blockId: number;
  blockOrderNumber: number;
  blockName: string;
  blockActive: boolean;
  blockWait: number;
  actions: string;
  instructionActive: boolean;
  parentId?: number;
  operation?: string;
  preComponent?: boolean;
  exportFile?: string;
  refreshLoop?: boolean;
  loopOnly?: boolean;
}

export interface ElementDTO {
  typeElement: string;
  tagName: string;
  xPath: string;
  someText: string;
  attribId: string;
  attribName: string;
  coordinates: string;
  attributeData: AttributeData[];
  customXPath: string;
  iFrameXPath: string;
  attributeValue: string;
  attributeType: string;
  searchAttributeValue: string;
}

export interface AttributeData {
  name: string;
  value: string;
}

export interface WebSocketMessage {
  type: string;
  body: any;
}

export interface ComplexMessage {
  parentNameWithId: string; // Format: "(parentId)parentName"
  connectionLabel: string;  // "Connected to:"
  actions: string;          // A string of actions, separated by commas
}


export interface UpdatedBlock {
  botJobId: number | null;  // Adjust the type based on actual data (use `null` if it's nullable)
  blockId: number;
  blockName: string;
  blockOrderNumber: number;
}

// Updated Block interface to include potential new fields in instructions
export interface Block {
  instructions: Array<{
    blockOrderNumber: number;
    blockActive: boolean;
    blockWait: number;
    [key: string]: any; // Include other properties if needed
  }>;
  [key: string]: any; // Add any other properties the block might have
}


export interface BotJobData {
  id: number;
  name: string;
  instructionId: number;
}

export const elementsDTOMockData: ElementDTO[] = [
  {
    "typeElement": "button",
    "tagName": "button",
    "xPath": "//button[@id='submit']",
    "someText": "Submit",
    "attribId": "submit",
    "attribName": "submitBtn",
    "coordinates": "100,200",
    "attributeData": [],
    "customXPath": "//button[contains(text(),'Submit')]",
    "iFrameXPath": "",
    "attributeValue": "enabled",
    "attributeType": "boolean",
    "searchAttributeValue": "submit"
  },
  {
    "typeElement": "input",
    "tagName": "input",
    "xPath": "//input[@name='username']",
    "someText": "",
    "attribId": "userInput",
    "attribName": "username",
    "coordinates": "150,250",
    "attributeData": [],
    "customXPath": "//input[@placeholder='Enter username']",
    "iFrameXPath": "",
    "attributeValue": "text",
    "attributeType": "string",
    "searchAttributeValue": "username"
  },
  {
    "typeElement": "input",
    "tagName": "input",
    "xPath": "//input[@type='password']",
    "someText": "",
    "attribId": "password",
    "attribName": "passwordInput",
    "coordinates": "150,280",
    "attributeData": [],
    "customXPath": "//input[@name='password']",
    "iFrameXPath": "",
    "attributeValue": "password",
    "attributeType": "string",
    "searchAttributeValue": "password"
  },
  {
    "typeElement": "div",
    "tagName": "div",
    "xPath": "//div[@class='alert']",
    "someText": "Error: Invalid login",
    "attribId": "",
    "attribName": "errorDiv",
    "coordinates": "160,300",
    "attributeData": [],
    "customXPath": "//div[contains(text(),'Error')]",
    "iFrameXPath": "",
    "attributeValue": "visible",
    "attributeType": "boolean",
    "searchAttributeValue": "alert"
  },
  {
    "typeElement": "a",
    "tagName": "a",
    "xPath": "//a[@href='/forgot-password']",
    "someText": "Forgot Password?",
    "attribId": "",
    "attribName": "forgotPwd",
    "coordinates": "170,320",
    "attributeData": [],
    "customXPath": "//a[contains(text(),'Forgot')]",
    "iFrameXPath": "",
    "attributeValue": "link",
    "attributeType": "string",
    "searchAttributeValue": "forgot-password"
  },
  {
    "typeElement": "label",
    "tagName": "label",
    "xPath": "//label[@for='username']",
    "someText": "Username:",
    "attribId": "",
    "attribName": "usernameLabel",
    "coordinates": "100,200",
    "attributeData": [],
    "customXPath": "//label[contains(text(),'Username')]",
    "iFrameXPath": "",
    "attributeValue": "text",
    "attributeType": "string",
    "searchAttributeValue": "usernameLabel"
  },
  {
    "typeElement": "select",
    "tagName": "select",
    "xPath": "//select[@id='country']",
    "someText": "",
    "attribId": "countrySelect",
    "attribName": "country",
    "coordinates": "200,350",
    "attributeData": [],
    "customXPath": "//select[@name='country']",
    "iFrameXPath": "",
    "attributeValue": "dropdown",
    "attributeType": "string",
    "searchAttributeValue": "country"
  },
  {
    "typeElement": "option",
    "tagName": "option",
    "xPath": "//option[@value='US']",
    "someText": "United States",
    "attribId": "",
    "attribName": "usOption",
    "coordinates": "210,360",
    "attributeData": [],
    "customXPath": "//option[contains(text(),'United States')]",
    "iFrameXPath": "",
    "attributeValue": "selected",
    "attributeType": "boolean",
    "searchAttributeValue": "US"
  },
  {
    "typeElement": "checkbox",
    "tagName": "input",
    "xPath": "//input[@type='checkbox' and @id='agree']",
    "someText": "",
    "attribId": "agree",
    "attribName": "agreeCheck",
    "coordinates": "220,370",
    "attributeData": [],
    "customXPath": "//input[@name='agree']",
    "iFrameXPath": "",
    "attributeValue": "checked",
    "attributeType": "boolean",
    "searchAttributeValue": "agree"
  },
  {
    "typeElement": "radio",
    "tagName": "input",
    "xPath": "//input[@type='radio' and @name='gender']",
    "someText": "",
    "attribId": "male",
    "attribName": "genderRadio",
    "coordinates": "230,380",
    "attributeData": [],
    "customXPath": "//input[@value='male']",
    "iFrameXPath": "",
    "attributeValue": "selected",
    "attributeType": "boolean",
    "searchAttributeValue": "male"
  },
  {
    "typeElement": "textarea",
    "tagName": "textarea",
    "xPath": "//textarea[@id='comments']",
    "someText": "",
    "attribId": "comments",
    "attribName": "commentsTextArea",
    "coordinates": "240,390",
    "attributeData": [],
    "customXPath": "//textarea[@name='comments']",
    "iFrameXPath": "",
    "attributeValue": "text",
    "attributeType": "string",
    "searchAttributeValue": "comments"
  },
  {
    "typeElement": "span",
    "tagName": "span",
    "xPath": "//span[@class='tooltip']",
    "someText": "Help text",
    "attribId": "",
    "attribName": "helpTooltip",
    "coordinates": "250,400",
    "attributeData": [],
    "customXPath": "//span[contains(text(),'Help')]",
    "iFrameXPath": "",
    "attributeValue": "visible",
    "attributeType": "boolean",
    "searchAttributeValue": "tooltip"
  },
  {
    "typeElement": "table",
    "tagName": "table",
    "xPath": "//table[@id='dataTable']",
    "someText": "",
    "attribId": "dataTable",
    "attribName": "dataTable",
    "coordinates": "260,410",
    "attributeData": [],
    "customXPath": "//table[contains(@class,'data-table')]",
    "iFrameXPath": "",
    "attributeValue": "structure",
    "attributeType": "string",
    "searchAttributeValue": "dataTable"
  },
  {
    "typeElement": "tr",
    "tagName": "tr",
    "xPath": "//tr[@class='row1']",
    "someText": "",
    "attribId": "",
    "attribName": "tableRow",
    "coordinates": "270,420",
    "attributeData": [],
    "customXPath": "//tr[contains(@class,'row1')]",
    "iFrameXPath": "",
    "attributeValue": "row",
    "attributeType": "string",
    "searchAttributeValue": "row1"
  },
  {
    "typeElement": "td",
    "tagName": "td",
    "xPath": "//td[@class='column1']",
    "someText": "Cell Data",
    "attribId": "",
    "attribName": "tableCell",
    "coordinates": "280,430",
    "attributeData": [],
    "customXPath": "//td[contains(@class,'column1')]",
    "iFrameXPath": "",
    "attributeValue": "text",
    "attributeType": "string",
    "searchAttributeValue": "column1"
  }
];

const instructionsMockData2: BlockLoopInstructionLoadDTO[] = [
  // {
  //   "id": 1137,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 1,
  //   "actions": "I:username",
  //   "name": "username",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1039,
  //   "blockOrderNumber": 1,
  //   "blockName": "Login",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1138,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 2,
  //   "actions": "I:password",
  //   "name": "password",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1039,
  //   "blockOrderNumber": 1,
  //   "blockName": "Login",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1139,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 3,
  //   "actions": "C",
  //   "name": "login",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1039,
  //   "blockOrderNumber": 1,
  //   "blockName": "Login",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1140,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 4,
  //   "actions": "PAUSE",
  //   "name": "PAUSE",
  //   "description": "PAUSE Action",
  //   "operation": "",
  //   "parentId": 0,
  //   "blockId": 1039,
  //   "blockOrderNumber": 1,
  //   "blockName": "Login",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1084,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 1,
  //   "actions": "C",
  //   "name": "conti e carta",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1024,
  //   "blockOrderNumber": 2,
  //   "blockName": "Conti e Carta",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1085,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 2,
  //   "actions": "C",
  //   "name": "Conti",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1024,
  //   "blockOrderNumber": 2,
  //   "blockName": "Conti e Carta",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1131,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 1,
  //   "actions": "C",
  //   "name": "open-divise",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1181,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 2,
  //   "actions": "H",
  //   "name": "Wait 2second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "parentId": 0,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1146,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 3,
  //   "actions": "C",
  //   "name": "AUD",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1183,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 4,
  //   "actions": "H",
  //   "name": "Wait 2second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "parentId": 0,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1117,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 5,
  //   "actions": "C",
  //   "name": "open-divise-AUD",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1176,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 6,
  //   "actions": "H",
  //   "name": "Wait 2second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "parentId": 0,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1106,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 7,
  //   "actions": "C",
  //   "name": "CHF",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1184,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 8,
  //   "actions": "H",
  //   "name": "Wait 2second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "parentId": 0,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1141,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 9,
  //   "actions": "C",
  //   "name": "OPEN-DIVISE-CHF",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1182,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 10,
  //   "actions": "H",
  //   "name": "Wait 2second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "parentId": 0,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1119,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 11,
  //   "actions": "C",
  //   "name": "ZAR",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1120,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 1,
  //   "actions": "C",
  //   "name": "OPEN-DIVISE-ZAR",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1034,
  //   "blockOrderNumber": 4,
  //   "blockName": "Open Divise ZAR",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1130,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 2,
  //   "actions": "C",
  //   "name": "CHF",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1034,
  //   "blockOrderNumber": 4,
  //   "blockName": "Open Divise ZAR",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1088,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 1,
  //   "actions": "C",
  //   "name": "carta di credito",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1025,
  //   "blockOrderNumber": 5,
  //   "blockName": "Carta di Credito",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1336,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 2,
  //   "actions": "H",
  //   "name": "Wait 5second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "parentId": 0,
  //   "blockId": 1025,
  //   "blockOrderNumber": 5,
  //   "blockName": "Carta di Credito",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1162,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 3,
  //   "actions": "C",
  //   "name": "autorizzo",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1025,
  //   "blockOrderNumber": 5,
  //   "blockName": "Carta di Credito",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1207,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 4,
  //   "actions": "H",
  //   "name": "Wait 2second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "parentId": 0,
  //   "blockId": 1025,
  //   "blockOrderNumber": 5,
  //   "blockName": "Carta di Credito",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1206,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 5,
  //   "actions": "C",
  //   "name": "credito proseguire",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1025,
  //   "blockOrderNumber": 5,
  //   "blockName": "Carta di Credito",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1208,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 1,
  //   "actions": "C",
  //   "name": "pagina iniziale",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1038,
  //   "blockOrderNumber": 6,
  //   "blockName": "Initiale",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1150,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 1,
  //   "actions": "C",
  //   "name": "nuovo pagamento",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1029,
  //   "blockOrderNumber": 7,
  //   "blockName": "Nuovo Pagamento",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1179,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 2,
  //   "actions": "H",
  //   "name": "Wait 2second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "parentId": 0,
  //   "blockId": 1029,
  //   "blockOrderNumber": 7,
  //   "blockName": "Nuovo Pagamento",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1151,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 3,
  //   "actions": "C",
  //   "name": "flag-svizerra",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1029,
  //   "blockOrderNumber": 7,
  //   "blockName": "Nuovo Pagamento",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1152,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 1,
  //   "actions": "I:iban",
  //   "name": "iban",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1031,
  //   "blockOrderNumber": 8,
  //   "blockName": "Iban",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1180,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 2,
  //   "actions": "H",
  //   "name": "Wait 2second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "parentId": 0,
  //   "blockId": 1031,
  //   "blockOrderNumber": 8,
  //   "blockName": "Iban",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1153,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 3,
  //   "actions": "I:nome",
  //   "name": "nome",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1031,
  //   "blockOrderNumber": 8,
  //   "blockName": "Iban",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1154,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 4,
  //   "actions": "I:indirizzo",
  //   "name": "indirizzo",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1031,
  //   "blockOrderNumber": 8,
  //   "blockName": "Iban",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1157,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 5,
  //   "actions": "C",
  //   "name": "iban-avanti",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1031,
  //   "blockOrderNumber": 8,
  //   "blockName": "Iban",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1026,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 1,
  //   "actions": "I:importo",
  //   "name": "importo",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1030,
  //   "blockOrderNumber": 9,
  //   "blockName": "Insert Importo",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1028,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 2,
  //   "actions": "C",
  //   "name": "avanti",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1030,
  //   "blockOrderNumber": 9,
  //   "blockName": "Insert Importo",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1337,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 3,
  //   "actions": "H",
  //   "name": "Wait 5second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "parentId": 0,
  //   "blockId": 1030,
  //   "blockOrderNumber": 9,
  //   "blockName": "Insert Importo",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1209,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 4,
  //   "actions": "C",
  //   "name": "inviare",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1030,
  //   "blockOrderNumber": 9,
  //   "blockName": "Insert Importo",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1160,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 1,
  //   "actions": "C",
  //   "name": "visualizzare detagli",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1032,
  //   "blockOrderNumber": 10,
  //   "blockName": "Visualizzare Detagli",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1032,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 1,
  //   "actions": "O:transaction",
  //   "name": "transaction",
  //   "description": "loop desc",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 0,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3,
  //   "loopOnly": true
  // },
  // {
  //   "id": 1056,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 2,
  //   "actions": "IF",
  //   "name": "IF",
  //   "description": "IF",
  //   "operation": "IF",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 1056,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1055,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 3,
  //   "actions": "CK",
  //   "name": "Check",
  //   "description": "Check Value",
  //   "operation": "$transaction:!\u003d:Condivise (SHA)",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 1032,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1033,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 4,
  //   "actions": "E",
  //   "name": "ExcelWrite",
  //   "description": "ExcelWrite",
  //   "operation": "ExcelWrite:$TRANSACTION",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 1032,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1057,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 5,
  //   "actions": "ELSE",
  //   "name": "ELSE",
  //   "description": "ELSE",
  //   "operation": "ELSE",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 1056,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1342,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 6,
  //   "actions": "C",
  //   "name": "pagamenti",
  //   "description": "loop desc",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 0,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1348,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 7,
  //   "actions": "H",
  //   "name": "Wait 5second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 0,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1344,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 8,
  //   "actions": "C",
  //   "name": "dettagli menu",
  //   "description": "loop desc",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 0,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1346,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 9,
  //   "actions": "H",
  //   "name": "Wait 5second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 0,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1345,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 10,
  //   "actions": "C",
  //   "name": "dettagli",
  //   "description": "loop desc",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 0,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1347,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 11,
  //   "actions": "H",
  //   "name": "Wait 5second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 0,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1339,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 12,
  //   "actions": "PAUSE",
  //   "name": "PAUSE",
  //   "description": "PAUSE Action",
  //   "operation": "",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 0,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1349,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 13,
  //   "actions": "LOOP",
  //   "name": "LOOP",
  //   "description": "LOOP",
  //   "operation": "5",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 1032,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1058,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 14,
  //   "actions": "ENDIF",
  //   "name": "ENDIF",
  //   "description": "ENDIF",
  //   "operation": "ENDIF",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 1056,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1205,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 15,
  //   "actions": "Q",
  //   "name": "Close Browser",
  //   "description": "Close Browser",
  //   "operation": "",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 0,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1340,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 16,
  //   "actions": "C",
  //   "name": "visualizarre tutto",
  //   "description": "loop desc",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 0,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": false,
  //   "instructionActive": false,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1350,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 17,
  //   "actions": "C",
  //   "name": "pagamenti menu",
  //   "description": "loop desc",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 0,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "instructionActive": true,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1061,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 1,
  //   "actions": "C",
  //   "name": "mercati e divise",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1010,
  //   "blockOrderNumber": 12,
  //   "blockName": "Mercati e Divise",
  //   "blockActive": false,
  //   "instructionActive": false,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1062,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 2,
  //   "actions": "C",
  //   "name": "informazioni finanziarie",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1010,
  //   "blockOrderNumber": 12,
  //   "blockName": "Mercati e Divise",
  //   "blockActive": false,
  //   "instructionActive": false,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1168,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 3,
  //   "actions": "C",
  //   "name": "circa search",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1010,
  //   "blockOrderNumber": 12,
  //   "blockName": "Mercati e Divise",
  //   "blockActive": false,
  //   "instructionActive": false,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1170,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 4,
  //   "actions": "C",
  //   "name": "circa search",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1010,
  //   "blockOrderNumber": 12,
  //   "blockName": "Mercati e Divise",
  //   "blockActive": false,
  //   "instructionActive": false,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1172,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 5,
  //   "actions": "I:circa input",
  //   "name": "circa input",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1010,
  //   "blockOrderNumber": 12,
  //   "blockName": "Mercati e Divise",
  //   "blockActive": false,
  //   "instructionActive": false,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1171,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 6,
  //   "actions": "C",
  //   "name": "circa button",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1010,
  //   "blockOrderNumber": 12,
  //   "blockName": "Mercati e Divise",
  //   "blockActive": false,
  //   "instructionActive": false,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1173,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 1,
  //   "actions": "C",
  //   "name": "search finanziarie",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1033,
  //   "blockOrderNumber": 13,
  //   "blockName": "Search Term",
  //   "blockActive": false,
  //   "instructionActive": false,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1174,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 2,
  //   "actions": "I:search term",
  //   "name": "search term",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1033,
  //   "blockOrderNumber": 13,
  //   "blockName": "Search Term",
  //   "blockActive": false,
  //   "instructionActive": false,
  //   "blockWait": 3
  // },
  // {
  //   "id": 1175,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 3,
  //   "actions": "C",
  //   "name": "search finanziarie",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1033,
  //   "blockOrderNumber": 13,
  //   "blockName": "Search Term",
  //   "blockActive": false,
  //   "instructionActive": false,
  //   "blockWait": 3
  // }
];

export default instructionsMockData2;

// export const botJobMockData: BotJobData = { id: 1, name: "FlatFox", data: 0 };
export const botJobMockData: BotJobData = {
  id: 0,
  name: "",
  instructionId: 0
};
