// Sample data (mocketData)
export interface BlockLoopInstructionLoadDTO {
  botJobId: number;
  botJobName: string;
  id: number;
  instructionOrderNumber: number;
  name: string;
  description: string;
  blockId: number;
  blockOrderNumber: number;
  blockName: string;
  blockActive: boolean;
  blockWait: number;
  actions: string;
  instructionActive: boolean;
  parentId?: number;
  operation?: string;
  preComponent?: boolean;
  exportFile?: string;
  refreshLoop?: boolean;
  loopOnly?: boolean;
}


export interface WebSocketMessage {
  type: string;
  body: any;
}
export interface ComplexMessage {
  parentNameWithId: string; // Format: "(parentId)parentName"
  connectionLabel: string;  // "Connected to:"
  actions: string;          // A string of actions, separated by commas
}

export interface UpdatedBlock {
  botJobId: number | null;  // Adjust the type based on actual data (use `null` if it's nullable)
  blockId: number;
  blockName: string;
  blockOrderNumber: number;
}

// Updated Block interface to include potential new fields in instructions
export interface Block {
  instructions: Array<{
    blockOrderNumber: number;
    blockActive: boolean;
    blockWait: number;
    [key: string]: any; // Include other properties if needed
  }>;
  [key: string]: any; // Add any other properties the block might have
}


export interface BotJobData {
  id: number;
  name: string;
  instructionId: number;
}

const instructionsMockData2: BlockLoopInstructionLoadDTO[] = [
  // {
  //   "id": 1137,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 1,
  //   "actions": "I:username",
  //   "name": "username",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1028,
  //   "blockOrderNumber": 1,
  //   "blockName": "Login",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1138,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 2,
  //   "actions": "I:password",
  //   "name": "password",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1028,
  //   "blockOrderNumber": 1,
  //   "blockName": "Login",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1139,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 3,
  //   "actions": "C",
  //   "name": "login",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1028,
  //   "blockOrderNumber": 1,
  //   "blockName": "Login",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1140,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 4,
  //   "actions": "PAUSE",
  //   "name": "PAUSE",
  //   "description": "PAUSE Action",
  //   "operation": "",
  //   "parentId": 0,
  //   "blockId": 1028,
  //   "blockOrderNumber": 1,
  //   "blockName": "Login",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1084,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 1,
  //   "actions": "C",
  //   "name": "conti e carta",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1024,
  //   "blockOrderNumber": 2,
  //   "blockName": "Conti e Carta",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1085,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 2,
  //   "actions": "C",
  //   "name": "Conti",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1024,
  //   "blockOrderNumber": 2,
  //   "blockName": "Conti e Carta",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1131,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 1,
  //   "actions": "C",
  //   "name": "open-divise",
  //   "description": "loop desc",
  //   "exportFile": "",
  //   "parentId": 0,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1181,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 2,
  //   "actions": "H",
  //   "name": "Wait 2second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "exportFile": "",
  //   "parentId": 0,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1211,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 3,
  //   "actions": "IF",
  //   "name": "IF",
  //   "description": "IF",
  //   "operation": "IF",
  //   "exportFile": "",
  //   "parentId": 1211,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1212,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 4,
  //   "actions": "ELSE",
  //   "name": "ELSE",
  //   "description": "ELSE",
  //   "operation": "ELSE",
  //   "exportFile": "",
  //   "parentId": 1211,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1213,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 5,
  //   "actions": "ENDIF",
  //   "name": "ENDIF",
  //   "description": "ENDIF",
  //   "operation": "ENDIF",
  //   "exportFile": "",
  //   "parentId": 1211,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1146,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 6,
  //   "actions": "C",
  //   "name": "AUD",
  //   "description": "loop desc",
  //   "exportFile": "",
  //   "parentId": 0,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1214,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 7,
  //   "actions": "IF",
  //   "name": "IF",
  //   "description": "IF",
  //   "operation": "IF",
  //   "exportFile": "",
  //   "parentId": 1214,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1215,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 8,
  //   "actions": "ELSE",
  //   "name": "ELSE",
  //   "description": "ELSE",
  //   "operation": "ELSE",
  //   "exportFile": "",
  //   "parentId": 1214,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1216,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 9,
  //   "actions": "ENDIF",
  //   "name": "ENDIF",
  //   "description": "ENDIF",
  //   "operation": "ENDIF",
  //   "exportFile": "",
  //   "parentId": 1214,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1183,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 10,
  //   "actions": "H",
  //   "name": "Wait 2second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "exportFile": "",
  //   "parentId": 0,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1117,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 11,
  //   "actions": "C",
  //   "name": "open-divise-AUD",
  //   "description": "loop desc",
  //   "exportFile": "",
  //   "parentId": 0,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1176,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 12,
  //   "actions": "H",
  //   "name": "Wait 2second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "exportFile": "",
  //   "parentId": 0,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1106,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 13,
  //   "actions": "C",
  //   "name": "CHF",
  //   "description": "loop desc",
  //   "exportFile": "",
  //   "parentId": 0,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1184,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 14,
  //   "actions": "H",
  //   "name": "Wait 2second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "exportFile": "",
  //   "parentId": 0,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1141,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 15,
  //   "actions": "C",
  //   "name": "OPEN-DIVISE-CHF",
  //   "description": "loop desc",
  //   "exportFile": "",
  //   "parentId": 0,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1182,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 16,
  //   "actions": "H",
  //   "name": "Wait 2second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "exportFile": "",
  //   "parentId": 0,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1119,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 17,
  //   "actions": "C",
  //   "name": "ZAR",
  //   "description": "loop desc",
  //   "exportFile": "",
  //   "parentId": 0,
  //   "blockId": 1027,
  //   "blockOrderNumber": 3,
  //   "blockName": "Open Divise",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1120,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 1,
  //   "actions": "C",
  //   "name": "OPEN-DIVISE-ZAR",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1034,
  //   "blockOrderNumber": 4,
  //   "blockName": "Open Divise ZAR",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1130,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 2,
  //   "actions": "C",
  //   "name": "CHF",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1034,
  //   "blockOrderNumber": 4,
  //   "blockName": "Open Divise ZAR",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1088,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 1,
  //   "actions": "C",
  //   "name": "carta di credito",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1025,
  //   "blockOrderNumber": 5,
  //   "blockName": "Carta di Credito",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1178,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 2,
  //   "actions": "H",
  //   "name": "Wait 2second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "parentId": 0,
  //   "blockId": 1025,
  //   "blockOrderNumber": 5,
  //   "blockName": "Carta di Credito",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1162,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 3,
  //   "actions": "C",
  //   "name": "autorizzo",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1025,
  //   "blockOrderNumber": 5,
  //   "blockName": "Carta di Credito",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1207,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 4,
  //   "actions": "H",
  //   "name": "Wait 2second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "parentId": 0,
  //   "blockId": 1025,
  //   "blockOrderNumber": 5,
  //   "blockName": "Carta di Credito",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1206,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 5,
  //   "actions": "C",
  //   "name": "credito proseguire",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1025,
  //   "blockOrderNumber": 5,
  //   "blockName": "Carta di Credito",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1208,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 1,
  //   "actions": "C",
  //   "name": "pagina iniziale",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1038,
  //   "blockOrderNumber": 6,
  //   "blockName": "Initiale",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1150,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 1,
  //   "actions": "C",
  //   "name": "nuovo pagamento",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1029,
  //   "blockOrderNumber": 7,
  //   "blockName": "Nuovo Pagamento",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1179,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 2,
  //   "actions": "H",
  //   "name": "Wait 2second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "parentId": 0,
  //   "blockId": 1029,
  //   "blockOrderNumber": 7,
  //   "blockName": "Nuovo Pagamento",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1151,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 3,
  //   "actions": "C",
  //   "name": "flag-svizerra",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1029,
  //   "blockOrderNumber": 7,
  //   "blockName": "Nuovo Pagamento",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1152,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 1,
  //   "actions": "I:iban",
  //   "name": "iban",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1031,
  //   "blockOrderNumber": 8,
  //   "blockName": "Iban",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1180,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 2,
  //   "actions": "H",
  //   "name": "Wait 2second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "parentId": 0,
  //   "blockId": 1031,
  //   "blockOrderNumber": 8,
  //   "blockName": "Iban",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1153,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 3,
  //   "actions": "I:nome",
  //   "name": "nome",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1031,
  //   "blockOrderNumber": 8,
  //   "blockName": "Iban",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1154,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 4,
  //   "actions": "I:indirizzo",
  //   "name": "indirizzo",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1031,
  //   "blockOrderNumber": 8,
  //   "blockName": "Iban",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1157,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 5,
  //   "actions": "C",
  //   "name": "iban-avanti",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1031,
  //   "blockOrderNumber": 8,
  //   "blockName": "Iban",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1026,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 1,
  //   "actions": "I:importo",
  //   "name": "importo",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1030,
  //   "blockOrderNumber": 9,
  //   "blockName": "Insert Importo",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1028,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 2,
  //   "actions": "C",
  //   "name": "avanti",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1030,
  //   "blockOrderNumber": 9,
  //   "blockName": "Insert Importo",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1210,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 3,
  //   "actions": "H",
  //   "name": "Wait 2second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "parentId": 0,
  //   "blockId": 1030,
  //   "blockOrderNumber": 9,
  //   "blockName": "Insert Importo",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1209,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 4,
  //   "actions": "C",
  //   "name": "inviare",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1030,
  //   "blockOrderNumber": 9,
  //   "blockName": "Insert Importo",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1160,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 1,
  //   "actions": "C",
  //   "name": "visualizzare detagli",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1032,
  //   "blockOrderNumber": 10,
  //   "blockName": "Visualizzare Detagli",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1032,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 1,
  //   "actions": "O:transaction",
  //   "name": "transaction",
  //   "description": "loop desc",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 0,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": true
  // },
  // {
  //   "id": 1185,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 2,
  //   "actions": "C",
  //   "name": "visualizzare recente",
  //   "description": "loop desc",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 0,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1188,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 3,
  //   "actions": "H",
  //   "name": "Wait 2second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 0,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1191,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 4,
  //   "actions": "C",
  //   "name": "in corso",
  //   "description": "loop desc",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 0,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1192,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 5,
  //   "actions": "H",
  //   "name": "Wait 2second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 0,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1198,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 6,
  //   "actions": "C",
  //   "name": "data di esecuzione",
  //   "description": "loop desc",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 0,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1199,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 7,
  //   "actions": "H",
  //   "name": "Wait 2second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 0,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1186,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 8,
  //   "actions": "C",
  //   "name": "first pgto",
  //   "description": "loop desc",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 0,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1189,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 9,
  //   "actions": "H",
  //   "name": "Wait 2second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 0,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1187,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 10,
  //   "actions": "C",
  //   "name": "dettagli",
  //   "description": "loop desc",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 0,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1190,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 11,
  //   "actions": "H",
  //   "name": "Wait 2second(s)",
  //   "description": "Waiting action",
  //   "operation": "",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 0,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1055,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 12,
  //   "actions": "CK",
  //   "name": "Check",
  //   "description": "Check Value",
  //   "operation": "$transaction:!\u003d:Condivise (SHA)",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 1032,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1041,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 13,
  //   "actions": "REFRESH_LOOP",
  //   "name": "Refresh Loop",
  //   "description": "Refresh Loop",
  //   "operation": "5:5",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 1032,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1033,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 14,
  //   "actions": "E",
  //   "name": "ExcelWrite",
  //   "description": "ExcelWrite",
  //   "operation": "ExcelWrite:$TRANSACTION",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 1032,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1205,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 15,
  //   "actions": "Q",
  //   "name": "Close Browser",
  //   "description": "Close Browser",
  //   "operation": "",
  //   "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/banca-stato.xlsx",
  //   "parentId": 0,
  //   "blockId": 1007,
  //   "blockOrderNumber": 11,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": true,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1061,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 1,
  //   "actions": "C",
  //   "name": "mercati e divise",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1010,
  //   "blockOrderNumber": 12,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": false,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1062,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 2,
  //   "actions": "C",
  //   "name": "informazioni finanziarie",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1010,
  //   "blockOrderNumber": 12,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": false,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1168,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 3,
  //   "actions": "C",
  //   "name": "circa search",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1010,
  //   "blockOrderNumber": 12,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": false,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1170,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 4,
  //   "actions": "C",
  //   "name": "circa search",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1010,
  //   "blockOrderNumber": 12,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": false,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1172,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 5,
  //   "actions": "I:circa input",
  //   "name": "circa input",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1010,
  //   "blockOrderNumber": 12,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": false,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1171,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 6,
  //   "actions": "C",
  //   "name": "circa button",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1010,
  //   "blockOrderNumber": 12,
  //   "blockName": "ExcelWrite Transaction",
  //   "blockActive": false,
  //   "blockWait": 3,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1173,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 1,
  //   "actions": "C",
  //   "name": "search finanziarie",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1033,
  //   "blockOrderNumber": 13,
  //   "blockName": "Search Term",
  //   "blockActive": false,
  //   "blockWait": 0,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1174,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 2,
  //   "actions": "I:search term",
  //   "name": "search term",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1033,
  //   "blockOrderNumber": 13,
  //   "blockName": "Search Term",
  //   "blockActive": false,
  //   "blockWait": 0,
  //   "refreshLoop": false
  // },
  // {
  //   "id": 1175,
  //   "botJobId": 1001,
  //   "botJobName": "BancaStato Pagamento",
  //   "instructionOrderNumber": 3,
  //   "actions": "C",
  //   "name": "search finanziarie",
  //   "description": "loop desc",
  //   "parentId": 0,
  //   "blockId": 1033,
  //   "blockOrderNumber": 13,
  //   "blockName": "Search Term",
  //   "blockActive": false,
  //   "blockWait": 0,
  //   "refreshLoop": false
  // }
];

export default instructionsMockData2;

// export const botJobMockData: BotJobData = { id: 1, name: "FlatFox", data: 0 };
export const botJobMockData: BotJobData = {
  id: 0,
  name: "",
  instructionId: 0
};
