// Sample data (mocketData)
export interface BlockLoopInstructionLoadDTO {
  botJobId: number;
  botJobName: string;
  id: number;
  instructionOrderNumber: number;
  name: string;
  description: string;
  blockId: number;
  blockOrderNumber: number;
  blockName: string;
  blockActive: boolean;
  blockWait: number;
  actions: string;
  instructionActive: boolean;
  parentId?: number;
  operation?: string;
  preComponent?: boolean;
  exportFile?: string;
  refreshLoop?: boolean;
  loopOnly?: boolean;
}


export interface WebSocketMessage {
  type: string;
  body: any;
}

export interface ComplexMessage {
  parentNameWithId: string; // Format: "(parentId)parentName"
  connectionLabel: string;  // "Connected to:"
  actions: string;          // A string of actions, separated by commas
}


export interface UpdatedBlock {
  botJobId: number | null;  // Adjust the type based on actual data (use `null` if it's nullable)
  blockId: number;
  blockName: string;
  blockOrderNumber: number;
}

// Updated Block interface to include potential new fields in instructions
export interface Block {
  instructions: Array<{
    blockOrderNumber: number;
    blockActive: boolean;
    blockWait: number;
    [key: string]: any; // Include other properties if needed
  }>;
  [key: string]: any; // Add any other properties the block might have
}


export interface BotJobData {
  id: number;
  name: string;
  instructionId: number;
}

const instructionsMockData2: BlockLoopInstructionLoadDTO[] = [
  {
    "id": 1214,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 1,
    "actions": "I:username",
    "name": "username",
    "description": "loop desc",
    "parentId": 0,
    "blockId": 1040,
    "blockOrderNumber": 1,
    "blockName": "CA Next Bank default block",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1215,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 2,
    "actions": "I:password",
    "name": "password",
    "description": "loop desc",
    "parentId": 0,
    "blockId": 1040,
    "blockOrderNumber": 1,
    "blockName": "CA Next Bank default block",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1216,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 3,
    "actions": "C",
    "name": "loginButton",
    "description": "loop desc",
    "parentId": 0,
    "blockId": 1040,
    "blockOrderNumber": 1,
    "blockName": "CA Next Bank default block",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1217,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 4,
    "actions": "PAUSE",
    "name": "PAUSE",
    "description": "PAUSE Action",
    "operation": "",
    "parentId": 0,
    "blockId": 1040,
    "blockOrderNumber": 1,
    "blockName": "CA Next Bank default block",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1218,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 1,
    "actions": "C",
    "name": "profile",
    "description": "loop desc",
    "parentId": 0,
    "blockId": 1041,
    "blockOrderNumber": 2,
    "blockName": "Change Language",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1221,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 2,
    "actions": "H",
    "name": "Wait 2second(s)",
    "description": "Waiting action",
    "operation": "",
    "parentId": 0,
    "blockId": 1041,
    "blockOrderNumber": 2,
    "blockName": "Change Language",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1219,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 3,
    "actions": "C",
    "name": "language selection",
    "description": "loop desc",
    "parentId": 0,
    "blockId": 1041,
    "blockOrderNumber": 2,
    "blockName": "Change Language",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1222,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 4,
    "actions": "H",
    "name": "Wait 2second(s)",
    "description": "Waiting action",
    "operation": "",
    "parentId": 0,
    "blockId": 1041,
    "blockOrderNumber": 2,
    "blockName": "Change Language",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1220,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 5,
    "actions": "I:select language",
    "name": "select language",
    "description": "loop desc",
    "parentId": 0,
    "blockId": 1041,
    "blockOrderNumber": 2,
    "blockName": "Change Language",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1225,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 6,
    "actions": "H",
    "name": "Wait 2second(s)",
    "description": "Waiting action",
    "operation": "",
    "parentId": 0,
    "blockId": 1041,
    "blockOrderNumber": 2,
    "blockName": "Change Language",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1223,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 7,
    "actions": "C",
    "name": "English",
    "description": "loop desc",
    "parentId": 0,
    "blockId": 1041,
    "blockOrderNumber": 2,
    "blockName": "Change Language",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1226,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 8,
    "actions": "H",
    "name": "Wait 2second(s)",
    "description": "Waiting action",
    "operation": "",
    "parentId": 0,
    "blockId": 1041,
    "blockOrderNumber": 2,
    "blockName": "Change Language",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1224,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 9,
    "actions": "C",
    "name": "changer",
    "description": "loop desc",
    "parentId": 0,
    "blockId": 1041,
    "blockOrderNumber": 2,
    "blockName": "Change Language",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1227,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 10,
    "actions": "H",
    "name": "Wait 2second(s)",
    "description": "Waiting action",
    "operation": "",
    "parentId": 0,
    "blockId": 1041,
    "blockOrderNumber": 2,
    "blockName": "Change Language",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1228,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 1,
    "actions": "C",
    "name": "new payment",
    "description": "loop desc",
    "parentId": 0,
    "blockId": 1042,
    "blockOrderNumber": 3,
    "blockName": "New Payment",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1231,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 2,
    "actions": "H",
    "name": "Wait 2second(s)",
    "description": "Waiting action",
    "operation": "",
    "parentId": 0,
    "blockId": 1042,
    "blockOrderNumber": 3,
    "blockName": "New Payment",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1229,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 3,
    "actions": "C",
    "name": "NEW ACCOUNT TRANSFER",
    "description": "loop desc",
    "parentId": 0,
    "blockId": 1042,
    "blockOrderNumber": 3,
    "blockName": "New Payment",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1232,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 4,
    "actions": "H",
    "name": "Wait 2second(s)",
    "description": "Waiting action",
    "operation": "",
    "parentId": 0,
    "blockId": 1042,
    "blockOrderNumber": 3,
    "blockName": "New Payment",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1230,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 5,
    "actions": "C",
    "name": "CREDIT ACCOUNT",
    "description": "loop desc",
    "parentId": 0,
    "blockId": 1042,
    "blockOrderNumber": 3,
    "blockName": "New Payment",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1234,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 6,
    "actions": "H",
    "name": "Wait 2second(s)",
    "description": "Waiting action",
    "operation": "",
    "parentId": 0,
    "blockId": 1042,
    "blockOrderNumber": 3,
    "blockName": "New Payment",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1233,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 7,
    "actions": "C",
    "name": "ACCOUNT",
    "description": "loop desc",
    "parentId": 0,
    "blockId": 1042,
    "blockOrderNumber": 3,
    "blockName": "New Payment",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1236,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 8,
    "actions": "H",
    "name": "Wait 2second(s)",
    "description": "Waiting action",
    "operation": "",
    "parentId": 0,
    "blockId": 1042,
    "blockOrderNumber": 3,
    "blockName": "New Payment",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1235,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 9,
    "actions": "I:AMOUNT",
    "name": "AMOUNT",
    "description": "loop desc",
    "parentId": 0,
    "blockId": 1042,
    "blockOrderNumber": 3,
    "blockName": "New Payment",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1237,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 10,
    "actions": "I:REASON",
    "name": "REASON",
    "description": "loop desc",
    "parentId": 0,
    "blockId": 1042,
    "blockOrderNumber": 3,
    "blockName": "New Payment",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1251,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 11,
    "actions": "H",
    "name": "Wait 2second(s)",
    "description": "Waiting action",
    "operation": "",
    "parentId": 0,
    "blockId": 1042,
    "blockOrderNumber": 3,
    "blockName": "New Payment",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1238,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 12,
    "actions": "C",
    "name": "NEXT",
    "description": "loop desc",
    "parentId": 0,
    "blockId": 1042,
    "blockOrderNumber": 3,
    "blockName": "New Payment",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1242,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 13,
    "actions": "H",
    "name": "Wait 2second(s)",
    "description": "Waiting action",
    "operation": "",
    "parentId": 0,
    "blockId": 1042,
    "blockOrderNumber": 3,
    "blockName": "New Payment",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1240,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 14,
    "actions": "C",
    "name": "SUBMIT",
    "description": "loop desc",
    "parentId": 0,
    "blockId": 1042,
    "blockOrderNumber": 3,
    "blockName": "New Payment",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1239,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 1,
    "actions": "C",
    "name": "NEXT CONFIRM",
    "description": "loop desc",
    "parentId": 0,
    "blockId": 1043,
    "blockOrderNumber": 4,
    "blockName": "Confirm Date",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1241,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 1,
    "actions": "C",
    "name": "VIEW DETAILS",
    "description": "loop desc",
    "parentId": 0,
    "blockId": 1044,
    "blockOrderNumber": 5,
    "blockName": "View Details",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1244,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 1,
    "actions": "C",
    "name": "Payments",
    "description": "loop desc",
    "parentId": 0,
    "blockId": 1045,
    "blockOrderNumber": 6,
    "blockName": "All Payments",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1250,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 2,
    "actions": "H",
    "name": "Wait 2second(s)",
    "description": "Waiting action",
    "operation": "",
    "parentId": 0,
    "blockId": 1045,
    "blockOrderNumber": 6,
    "blockName": "All Payments",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1245,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 3,
    "actions": "C",
    "name": "ALL",
    "description": "loop desc",
    "parentId": 0,
    "blockId": 1045,
    "blockOrderNumber": 6,
    "blockName": "All Payments",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1249,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 4,
    "actions": "H",
    "name": "Wait 2second(s)",
    "description": "Waiting action",
    "operation": "",
    "parentId": 0,
    "blockId": 1045,
    "blockOrderNumber": 6,
    "blockName": "All Payments",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1246,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 5,
    "actions": "C",
    "name": "OPEN DETAILS",
    "description": "loop desc",
    "parentId": 0,
    "blockId": 1045,
    "blockOrderNumber": 6,
    "blockName": "All Payments",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1248,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 6,
    "actions": "H",
    "name": "Wait 2second(s)",
    "description": "Waiting action",
    "operation": "",
    "parentId": 0,
    "blockId": 1045,
    "blockOrderNumber": 6,
    "blockName": "All Payments",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1247,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 7,
    "actions": "C",
    "name": "VIEW",
    "description": "loop desc",
    "parentId": 0,
    "blockId": 1045,
    "blockOrderNumber": 6,
    "blockName": "All Payments",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1252,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 1,
    "actions": "IF",
    "name": "IF",
    "description": "IF",
    "operation": "IF",
    "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/credito agricola.xlsx",
    "parentId": 1252,
    "blockId": 1046,
    "blockOrderNumber": 7,
    "blockName": "Check Transaction",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1243,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 2,
    "actions": "O:reference number",
    "name": "reference number",
    "description": "loop desc",
    "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/credito agricola.xlsx",
    "parentId": 0,
    "blockId": 1046,
    "blockOrderNumber": 7,
    "blockName": "Check Transaction",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1258,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 3,
    "actions": "E",
    "name": "ExcelWrite",
    "description": "ExcelWrite",
    "operation": "ExcelWrite:$REFERENCE NUMBER",
    "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/credito agricola.xlsx",
    "parentId": 1243,
    "blockId": 1046,
    "blockOrderNumber": 7,
    "blockName": "Check Transaction",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1253,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 4,
    "actions": "ELSE",
    "name": "ELSE",
    "description": "ELSE",
    "operation": "ELSE",
    "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/credito agricola.xlsx",
    "parentId": 1252,
    "blockId": 1046,
    "blockOrderNumber": 7,
    "blockName": "Check Transaction",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1255,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 5,
    "actions": "H",
    "name": "Wait 5second(s)",
    "description": "Waiting action",
    "operation": "",
    "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/credito agricola.xlsx",
    "parentId": 0,
    "blockId": 1046,
    "blockOrderNumber": 7,
    "blockName": "Check Transaction",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1256,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 6,
    "actions": "GOTO",
    "name": "GOTO",
    "description": "GOTO",
    "operation": "6# All Payments",
    "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/credito agricola.xlsx",
    "parentId": 1045,
    "blockId": 1046,
    "blockOrderNumber": 7,
    "blockName": "Check Transaction",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1254,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 7,
    "actions": "ENDIF",
    "name": "ENDIF",
    "description": "ENDIF",
    "operation": "ENDIF",
    "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/credito agricola.xlsx",
    "parentId": 1252,
    "blockId": 1046,
    "blockOrderNumber": 7,
    "blockName": "Check Transaction",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  },
  {
    "id": 1257,
    "botJobId": 1032,
    "botJobName": "CA Next Bank",
    "instructionOrderNumber": 8,
    "actions": "PAUSE",
    "name": "PAUSE",
    "description": "PAUSE Action",
    "operation": "",
    "exportFile": "D:/Projects/AllinWeb/ABRWeb/Export/credito agricola.xlsx",
    "parentId": 0,
    "blockId": 1046,
    "blockOrderNumber": 7,
    "blockName": "Check Transaction",
    "blockActive": true,
    "instructionActive": true,
    "blockWait": 3
  }
];

export default instructionsMockData2;

// export const botJobMockData: BotJobData = { id: 1, name: "FlatFox", data: 0 };
export const botJobMockData: BotJobData = {
  id: 0,
  name: "",
  instructionId: 0
};
