import React, { useMemo, useState } from 'react';
import { CheckCheck, X } from 'lucide-react';
import styles from './OCRTestResultsPanel.module.scss';
import './OCRFloatingPanel.scss';
export type OCRTestRow={definedName:string;quality:string;tag:string;domText:string;ocrText:string;xPath:string};
export type OCRTestResult={source:string;wordCount:number;counts:Record<string,number>;rows:OCRTestRow[];annotatedImage?:string};
type Props={result:OCRTestResult;onAccept:(suggestions:Array<{xPath:string;clientNamed:string}>)=>void;onClose:()=>void};
const OCRTestResultsPanel:React.FC<Props>=({result,onAccept,onClose})=>{
 const [approved,setApproved]=useState<Set<string>>(new Set()); const [selected,setSelected]=useState<OCRTestRow|null>(result.rows[0]||null);
 const all=approved.size===result.rows.length; const suggestions=useMemo(()=>result.rows.filter(r=>approved.has(r.xPath)&&r.ocrText.trim()&&r.ocrText.trim().toLowerCase()!==r.definedName?.trim().toLowerCase()).map(r=>({xPath:r.xPath,clientNamed:r.ocrText.trim()})),[approved,result.rows]);
 const toggle=(path:string)=>setApproved(current=>{const next=new Set(current);next.has(path)?next.delete(path):next.add(path);return next;});
 return <div className={styles.backdrop}><section className={styles.panel} aria-label="OCR test results"><header><div><strong>OCR test results</strong><small>{result.source} · {result.wordCount} words · {approved.size}/{result.rows.length} approved</small></div><button title="Close" onClick={onClose}><X size={18}/></button></header><div className={styles.summary}>{['EXACT_CONTAIN','OVERLAP','PROXIMITY','NONE'].map(q=><span key={q} data-quality={q}>{q.replace('_',' ')} <b>{result.counts[q]||0}</b></span>)}</div><div className={styles.content}><div className={styles.tableWrap}><table><thead><tr><th>Approved</th><th>Name</th><th>Quality</th><th>Tag</th><th>DOM text</th><th>OCR text</th></tr></thead><tbody>{result.rows.map(row=><tr key={row.xPath} onClick={()=>setSelected(row)} className={selected?.xPath===row.xPath?styles.selected:''}><td><input aria-label={`Approve ${row.definedName}`} type="checkbox" checked={approved.has(row.xPath)} onChange={()=>toggle(row.xPath)}/></td><td>{row.definedName}</td><td><span data-quality={row.quality}>{row.quality}</span></td><td>{row.tag}</td><td>{row.domText}</td><td>{row.ocrText}</td></tr>)}</tbody></table></div><aside>{result.annotatedImage?<img src={result.annotatedImage} alt="OCR annotated scanner result"/>:<p>No annotated image generated.</p>}</aside></div><div className={styles.xpath}><strong>Full XPath</strong><input readOnly value={selected?.xPath||''}/></div><footer><button onClick={()=>setApproved(all?new Set():new Set(result.rows.map(r=>r.xPath)))}>{all?'Clear all':'Mark all approved'}</button><span/><button className={styles.primary} disabled={!suggestions.length} onClick={()=>onAccept(suggestions)}><CheckCheck size={15}/>Accept OCR names ({suggestions.length})</button></footer></section></div>;
};
export default OCRTestResultsPanel;
